export default [
    { id: 1, sweetTask: 'Take a 15-minute walk outside.' },
    { id: 2, sweetTask: 'Write down 3 things you\'re grateful for.' },
    { id: 3, sweetTask: 'Read at least one page of a book.' },
    { id: 4, sweetTask: 'Smile at a stranger.' },
    { id: 5, sweetTask: 'Say hello to someone new.' },
    { id: 6, sweetTask: 'Drink an extra glass of water.' },
    { id: 7, sweetTask: 'Take 10 deep breaths.' },
    { id: 8, sweetTask: 'Tidy up one small area around you.' },
    { id: 9, sweetTask: 'Listen to a new song in a genre you don’t usually pick.' },
    { id: 10, sweetTask: 'Compliment someone today.' },
    { id: 11, sweetTask: 'Send a short message to a friend or family member.' },
    { id: 12, sweetTask: 'Spend 10 minutes without your phone.' },
    { id: 13, sweetTask: 'Draw something simple (even just a stick figure).' },
    { id: 14, sweetTask: 'Send someone a funny meme.' },
    { id: 15, sweetTask: 'Look through old photos and remember a good moment.' },
    { id: 16, sweetTask: 'Do a short stretching session (5 minutes).' },
    { id: 17, sweetTask: 'Hold the door open for someone.' },
    { id: 18, sweetTask: 'Set and complete one tiny goal for today.' },
    { id: 19, sweetTask: 'Sit quietly for 5 minutes and do nothing.' },
    { id: 20, sweetTask: 'Write down one positive thing that happened today.' },
    { id: 21, sweetTask: 'Try a new type of tea or coffee.' },
    { id: 22, sweetTask: 'Organize one folder on your phone or computer.' },
    { id: 23, sweetTask: 'Compliment yourself out loud.' },
    { id: 24, sweetTask: 'Spend 5 minutes looking at the sky.' },
    { id: 25, sweetTask: 'Say "thank you" with extra sincerity.' },
    { id: 26, sweetTask: 'Learn one new word and use it in a sentence.' },
    { id: 27, sweetTask: 'Give yourself permission to rest for 10 minutes.' },
    { id: 28, sweetTask: 'Listen to a short motivational podcast or quote.' },
    { id: 29, sweetTask: 'Help someone without expecting anything back.' },
    { id: 30, sweetTask: 'Imagine one dream you have — and take one tiny step toward it.' },
];