export default [
    { id: 1, sweetReward: 'I am moving forward one step at a time.' },
    { id: 2, sweetReward: 'I am proud of the small progress I make every day.' },
    { id: 3, sweetReward: 'I choose kindness for myself and others.' },
    { id: 4, sweetReward: 'I am capable of achieving my dreams.' },
    { id: 5, sweetReward: 'I trust my journey, even when it feels slow.' },
    { id: 6, sweetReward: 'I am enough exactly as I am today.' },
    { id: 7, sweetReward: 'I allow myself to grow at my own pace.' },
    { id: 8, sweetReward: 'I radiate positivity and strength.' },
    { id: 9, sweetReward: 'Every small step brings me closer to my goals.' },
    { id: 10, sweetReward: 'I am creating a life I love.' },
    { id: 11, sweetReward: 'I welcome new opportunities with an open heart.' },
    { id: 12, sweetReward: 'I am patient with myself and my growth.' },
    { id: 13, sweetReward: 'I celebrate even my smallest victories.' },
    { id: 14, sweetReward: 'I have the courage to keep going.' },
    { id: 15, sweetReward: 'I am grateful for my journey and lessons.' },
    { id: 16, sweetReward: 'I believe in my ability to change and evolve.' },
    { id: 17, sweetReward: 'I choose progress over perfection.' },
    { id: 18, sweetReward: 'I honor my effort, no matter how small.' },
    { id: 19, sweetReward: 'I am building a beautiful future step by step.' },
    { id: 20, sweetReward: 'I am proud of who I am becoming.' },
];